/**
 * Write down which brand files actually exist, before the app is built.
 *
 * The logo component tries the real artwork first and falls back to a drawn
 * stand-in. Probing for it in the browser worked, but every page load fired a
 * 404 per candidate — four of them on any page with the lockup — which is noise
 * in the console and a wasted request each time.
 *
 * So the check happens here instead, at build time, where the filesystem can
 * answer it for free. Drop a file into public/brand/ and the next build picks it
 * up; until then the component never asks for it.
 */
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brandDir = join(root, "public", "brand");
const out = join(root, "lib", "brand-assets.ts");

let files = [];
try {
  files = readdirSync(brandDir).filter(f => /\.(svg|png|jpg|jpeg|webp)$/i.test(f));
} catch {
  // No public/brand yet — that is the normal state before any artwork lands.
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// GENERATED by scripts/brand-assets.mjs — do not edit.
// Brand artwork present in public/brand at build time.
export const BRAND_FILES: readonly string[] = ${JSON.stringify(files.map(f => `/brand/${f}`), null, 2)} as const;
`);
console.log(`brand assets: ${files.length ? files.join(", ") : "none — using the drawn stand-in"}`);
